---
title: "Speaker WebPPL Model"
author: "Ben Morris and Dan Yurovsky"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: true
    toc_float:
      collapsed: true
    code_folding: hide
---


Setup
```{r, include=FALSE}
knitr::opts_chunk$set(fig.align='center', echo=FALSE, messages=FALSE, warning = FALSE,
                      fig.height = 3, fig.width=5)

theme_set(theme_bw(base_size = 14) + theme(panel.grid = element_blank(),
                  strip.background = element_blank()))

#Load packages + setup
library(rwebppl)
library(tidyverse)
library(ggjoy)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

Run Model (or read in saved copy below)
```{r}
library(RCurl)
full_implicit <- read.csv(text =getURL("https://rawgit.com/benjamincmorris/reference-game/master/turk/2017.5.9_sender_full/5.9_data_anon.csv"))



##read in empirical data to feed model
empiricalVocabsConds<- read.csv("empiricalVocabsFull.csv") %>%
  select(-X)
# ### this line runs webppl model
# t1 <- proc.time()
outcomes<-webppl(program_file = "speaker.wppl", data=empiricalVocabsConds, data_var = "empiricalVocabs")
# proc.time() - t1
# 
# ### clean up data from model
gamePredictions <- outcomes %>%
  # unnest(predictions, pred_perf_teaching, pred_perf_partner, gameTrials) %>%
  unnest(pred_perf_teaching, gameTrials) %>%
    cbind(appearance= rep.int(c(1,2,3), nrow(.)/3))



```

Read In and Join Empirical Data
```{r}
###full empirical dataset
full_empirical <- read.csv('empirical_data/5.12_data_anon.csv') %>% select(-X)

###join empirical data and model predictions
all_data <- full_empirical %>%
  filter(ldf_num %in% gamePredictions$me) %>%
  select(-partnersExposure) %>%
  filter(toBeDropped != 1) %>%
  group_by(ldf_num, exposureRate, targetObjectName) %>%
  mutate(appearance = if_else(trialnum == min(trialnum), 1,
                              if_else(trialnum == max(trialnum), 3, 2))) %>%
  left_join(gamePredictions, by=c('ldf_num'='me', 'realLabel'='gameTrials', 'appearance')) %>%
  mutate(method=ifelse(method=='click', "point",
                        ifelse(method=="label","speak", "teach"))) %>%
  as.data.frame(.)

```


Or read in model predictions from saved copy
```{r}
###read in model data from csv
all_data <- read.csv("5.12_three_models.csv") %>% select(-X)
# all_data <- read.csv("fixed_teach_cost.csv") %>% select(-X)

```


Plot 1: Method Choice as a function of Appearance, split by Utility Condition
```{r}
seprop <- function(props) {
  mean_prop = mean(props)
  sqrt( (mean_prop*(1 - mean_prop)) / length(props))
}


modality.colors <- c(speak = "#e8250b", point = "#1f11e0", teach ="#fc8702", speech = "#e8250b", gesture = "#1f11e0", both ="#fc8702")



###wrangling data for plots by exposure
prop_methods_exposures <- all_data %>%
  filter(toBeDropped != 1) %>%
  # filter(partnersExposure == 0) %>%
  ungroup() %>%
  select(condition,ldf_num, partnersExposure, exposureRate,method) %>%
  gather(isEmpirical, method, -condition, -partnersExposure, -ldf_num, -exposureRate) %>%
  group_by(condition, ldf_num,partnersExposure, exposureRate,isEmpirical, method) %>%
  summarise(n = n()) %>%
  group_by(condition, ldf_num,partnersExposure, isEmpirical, exposureRate) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(method)) %>%
  tidyr::complete(nesting(condition, ldf_num, partnersExposure), isEmpirical, exposureRate, method, fill = list(n = 0)) %>%
  group_by(condition, partnersExposure, method, isEmpirical, exposureRate) %>%
  summarise(mean = mean(n), se = seprop(n)) 

prop_methods_exposures %>% 
  ungroup() %>%
  filter(method!='teach') %>%
  filter(partnersExposure==2) %>%
  mutate(condition=factor(condition,labels=c('Talk is Cheap', 'Talk is Less Cheap'))) %>%
  mutate(exposureRate=as.factor(exposureRate))%>%
  mutate(exposureRate=factor(exposureRate, levels=c(4,2,1))) %>%
  ggplot(aes(x=exposureRate, y=mean)) +
  geom_point(aes(color=method),size=2.25,position=position_dodge(.25)) +
  geom_line(aes(x=(exposureRate), y=mean, group=interaction(method,condition), color=method),  size=1, position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se, color=method), position=position_dodge(.25)) +
  # facet_grid(partnersExposure ~ condition) +
  labs(y="Proportion of Trials", x="Exposure Rate") +
  coord_cartesian(ylim=c(0,1)) +
  facet_wrap(~condition) +
  # scale_alpha(range = c(0.4, 0.8)) +
  theme_bw() +
  scale_color_manual(values=modality.colors,
                     name = "Modality", 
                    labels=c("Gesture", "Speak")) 


###plot of method choice as a function of appearance, split across point conditions
# to_be_plotted <- prop_methods %>% 
#   filter(partnersExposure==.5) %>%
#   filter(method!='teach')
# 
# to_be_plotted %>% filter(isEmpirical=='method') %>%
#   ggplot(aes(x=appearance, y=mean)) +
#   geom_line(aes(x=as.factor(appearance), y=mean, group=interaction(method,condition), color=method, shape=condition), position=position_dodge(.25)) +
#   geom_pointrange(aes(ymax = mean + se,
#     ymin = mean - se, color=method, alpha=condition), position=position_dodge(.25)) +
#   # facet_grid(partnersExposure ~ condition) +
#   labs(y="Proportion of Trials", x="Object Appearance #") +
#   coord_cartesian(ylim=c(0,1)) +
#   # geom_ribbon(data=(to_be_plotted %>% filter(isEmpirical=="pred_perf_teaching")),
#               # aes(x=as.numeric(appearance),ymax = mean + se,
#                       # ymin = mean - se, fill=method, alpha=.4), position=position_dodge(.25)) +
#   # facet_wrap(~condition) +
#     scale_fill_brewer(name = "Condition", 
#                     labels=c("Talk is Cheap", "Talk is More Expensive"),
#                     palette = "Set1") +
#   theme_bw()


```


Teaching Plot Across Conditions
```{r}
###wrangling data for teaching
prop_methods <- all_data %>%
  filter(toBeDropped != 1) %>%
  # filter(partnersExposure == 0) %>%
  ungroup() %>%
  # select(condition,ldf_num, partnersExposure, appearance,method,predictions, pred_perf_partner, pred_perf_teaching) %>%
  select(condition,ldf_num, partnersExposure, appearance,method) %>%
  gather(isEmpirical, method, -condition, -partnersExposure, -ldf_num, -appearance) %>%
  group_by(condition, ldf_num,partnersExposure, appearance,isEmpirical, method) %>%
  summarise(n = n()) %>%
  group_by(condition, ldf_num,partnersExposure, isEmpirical, appearance) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(method)) %>%
  tidyr::complete(nesting(condition, ldf_num, partnersExposure), isEmpirical, appearance, method, fill = list(n = 0)) %>%
  group_by(condition, partnersExposure, method, isEmpirical, appearance) %>%
  summarise(mean = mean(n), se = seprop(n))

prop_methods %>%
  filter(method=='teach', isEmpirical=='method', condition=="100_30") %>%
  ungroup() %>%
  mutate(partnersExposure=factor(partnersExposure, labels=c('None', 'Half', 'Twice'))) %>%
  mutate(appearance=as.factor(appearance)) %>%
  ggplot(aes(x=appearance, y=mean, label=partnersExposure)) +
  geom_point(aes(x=appearance, y=mean, color=partnersExposure), size=2.25, position=position_dodge(.25)) +
  geom_line(aes(x=appearance, y=mean, group=partnersExposure, color=partnersExposure), size=1, position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se, color=partnersExposure), position=position_dodge(.25)) +
  # facet_grid(partnersExposure ~ condition) +
  labs(y="Teaching Trials (Proportion)", x="Object Appearance #") +
  coord_cartesian(ylim=c(0,1)) +
  geom_dl(aes(label = partnersExposure, color=partnersExposure), method=list("first.qp", hjust=c(1.05, 1.45, 1.5), cex = .9)) +
  scale_color_manual(values=c("#87d868", "#54a832", "#2c6d12"), name = "Partner's Exposure", 
                    labels=c("None", "Half as Much", "Twice as Much")) 
  # geom_ribbon(data=(to_be_plotted %>% filter(isEmpirical=="pred_perf_teaching")),
              # aes(x=as.numeric(appearance),ymax = mean + se,
                      # ymin = mean - se, fill=method, alpha=.4), position=position_dodge(.25)) +
  # facet_wrap(~condition) 
```



Teaching Plot by Exposure Rate
First Trial ONLY
```{r}
###wrangling data for teaching
prop_methods_exposures <- all_data %>%
  filter(toBeDropped != 1) %>%
  filter(appearance == 1) %>%
  ungroup() %>%
  # select(condition,ldf_num, partnersExposure, exposureRate,method,predictions, pred_perf_partner, pred_perf_teaching) %>%
  select(condition,ldf_num, partnersExposure, exposureRate,method) %>%
  gather(isEmpirical, method, -condition, -partnersExposure, -ldf_num, -exposureRate) %>%
  group_by(condition, ldf_num,partnersExposure, exposureRate,isEmpirical, method) %>%
  summarise(n = n()) %>%
  group_by(condition, ldf_num,partnersExposure, isEmpirical, exposureRate) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(method)) %>%
  tidyr::complete(nesting(condition, ldf_num, partnersExposure), isEmpirical, exposureRate, method, fill = list(n = 0)) %>%
  group_by(condition, partnersExposure, method, isEmpirical, exposureRate) %>%
  summarise(mean = mean(n), se = seprop(n))

prop_methods_exposures %>%
  filter(method=='teach', isEmpirical=='method', condition=="100_30") %>%
  ungroup() %>%
  mutate(partnersExposure=factor(partnersExposure, labels=c('None', 'Half', 'Twice'))) %>%
  mutate(exposureRate=factor(exposureRate, levels=c(4,2,1))) %>%
  ggplot(aes(x=exposureRate, y=mean, label=partnersExposure)) +
  geom_point(aes(x=exposureRate, y=mean, color=partnersExposure), size=2.25, position=position_dodge(.25)) +
  geom_line(aes(x=exposureRate, y=mean, group=partnersExposure, color=partnersExposure), size=1, position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se, color=partnersExposure), position=position_dodge(.25)) +
  # facet_grid(partnersExposure ~ condition) +
  labs(y="Teaching Trials (Proportion)", x="Exposure Rate") +
  coord_cartesian(ylim=c(0,1)) +
  geom_dl(aes(label = partnersExposure, color=partnersExposure), method=list("first.qp", hjust=c(1.05, 1.45, 1.5), cex = .9)) +
  scale_color_manual(values=c("#87d868", "#54a832", "#2c6d12"), name = "Partner's Exposure", 
                    labels=c("None", "Half as Much", "Twice as Much")) 
  # geom_ribbon(data=(to_be_plotted %>% filter(isEmpirical=="pred_perf_teaching")),
              # aes(x=as.numeric(appearance),ymax = mean + se,
                      # ymin = mean - se, fill=method, alpha=.4), position=position_dodge(.25)) +
  # facet_wrap(~condition) 
```





To-Do: Make Linear Plot of Model Predictions vs. Empirical Data
```{r}
prop_methods_perf_teach <- prop_methods %>%
  filter(isEmpirical=='pred_perf_teaching')




###direct plot of model fit
model_fit <- prop_methods %>%
  ungroup() %>%
  mutate(isEmpirical= ifelse(isEmpirical=='method', 'empirical', isEmpirical)) %>%
  unite(mean_new, mean, se) %>%
  spread(isEmpirical, mean_new) %>% 
  separate(empirical, c('mean_emp', 'se_emp'), '_') %>%
  separate(predictions, c('mean_pred', 'se_pred'), '_') %>%
  separate(pred_perf_teaching, c('mean_pred_teach', 'se_pred_teach'), '_') %>%
  separate(pred_perf_partner, c('mean_pred_partner', 'se_pred_partner'), '_') %>%
  mutate_if(grepl('_', names(.)), as.numeric)


residuals <- model_fit %>%
  mutate(residual = (mean_emp -mean_pred_partner)^2) %>%
  group_by(partnersExposure, method, condition, appearance) %>%
  summarise(residual = mean(residual)) %>%
  summarise(residual = sqrt(sum(residual)))


ggplot(residuals, aes(x =as.factor(partnersExposure), y = residual, color = method)) + 
  geom_point()

model_fit %>%
  ggplot(aes(x=mean_pred_teach, y=mean_emp, color=method, shape=as.factor(condition),
             label = appearance)) +
  geom_abline(intercept =0, slope=1) +
  # geom_linerange(aes(ymax = mean_emp + se_emp, 
  #                    ymin = mean_emp - se_emp),
  #                 position=position_dodge(.25)) + 
  # geom_errorbarh(aes(xmin = mean_pred_teach - se_pred_teach,
  #                    xmax = mean_pred_teach + se_pred_teach),
  #                 position=position_dodge(.25),
  #                alpha = .5)+
  geom_label() +
  #geom_point() + 
  coord_cartesian(xlim=c(0,1), ylim=c(0,1))


model_fit %>%
  summarise(cor = cor(mean_emp, mean_pred_teach))

```



```{r}
# tmp <- getURL("https://raw.githubusercontent.com/dyurovsky/gesture/master/feathers/coded_responses.feather")
corpus_data <- read_feather('~/Downloads/coded_responses.feather')

corpus_methods <- corpus_data %>%
  group_by(subj,person,age, modality) %>%
  summarise(n = n()) %>%
  group_by(subj,person,age) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(modality)) %>%
  # tidyr::complete(nesting(subj, age), person, method, fill = list(n = 0)) %>%
  group_by(age,person, method) %>%
  summarise(mean = mean(n), se = seprop(n))


###plot of method choice as a function of appearance, split across point conditions
corpus_plot <- corpus_data %>%
  filter(person=='parent') %>% 
      select(age,freq_cut, subj, modality, referent) %>%
  group_by(age,freq_cut, subj, modality, referent) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(modality=as.factor(modality)) %>%
  tidyr::complete(nesting(age,freq_cut,referent, subj), modality, fill = list(n = 0)) %>%
  group_by(age, freq_cut, subj, referent) %>%
  mutate(n = n/sum(n)) %>%
  group_by(age, freq_cut,  modality,  subj) %>%
  summarise(n = mean(n)) %>%
  summarise(mean = mean(n), se= seprop(n))


corpus_plot$freq_cut_interp <- factor(corpus_plot$freq_cut, levels(corpus_plot$freq_cut), labels=c('Most Rare', 'Rare-ish', 'Freq-ish', 'Most Frequent'))
corpus_plot$freq_cut_interp <- factor(corpus_plot$freq_cut_interp, levels=c( 'Most Frequent','Freq-ish', 'Rare-ish','Most Rare'))


corpus_plot %>%
  filter(age==14|age==22) %>%
  ungroup() %>%
  filter(modality=='both') %>%
  mutate(age=as.factor(age))%>%
  mutate(age=factor(age, labels=c('14 mo', '22 mo'))) %>%
  ggplot(aes(x=freq_cut_interp, y=mean, group=age)) +
  geom_point(aes(color=age), size=3.25, position=position_dodge(.25)) +
  geom_line(aes(x=freq_cut_interp, y=mean,  color=age), size=1.25,  position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se, color=age),position=position_dodge(.25)) +
  labs(y="Proportion of References \n using Gesture + Speech", x=NULL) +
  # coord_cartesian(ylim=c(0,1)) +
  # facet_grid(.~age) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 25, hjust = 1)) +
  scale_color_manual(values=c("#87d868", "#54a832", "#2c6d12"))
```




