---
title: "Gesture-Speech Model Simulations"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r load-libraries}
library(tidyverse)
library(tidyboot)
library(DescTools)

theme_set(theme_classic(base_size = 14))

```

```{r teaching}
teach_learn_p <- function(p , n) {
  1 - (1-p) ^ n
}

teach_learn_prop <- function(p) {
  tibble(n = 1:50, prob = map(1:50, ~teach_learn_p(p, .x)) 
         %>% unlist()) %>%
    mutate(p = p)
}


teach_props <- map_df(seq(.25,.75,.25), ~teach_learn_prop(.x))

# ggplot(teach_props, aes(x = n, y = prob, color = as.factor(p))) + 
#   geom_line()
```

```{r xsit, eval = F, include = F}
generate_xsit_stims <- function(C = 4, M = 16, n = 100) {
  
  stims <- tibble(item = 2:M, count = 0) %>%
    mutate(trial = 0)
  
  for(i in 1:n) {
    
    last_trial <- stims %>%
      filter(trial == i -1)
    
    increment <- sample(last_trial %>% pull(item), C - 1)
      
    this_trial <- last_trial %>%
      mutate(count = if_else(item %in% increment, count + 1, count),
             trial = trial + 1)
    
    stims <- bind_rows(stims, this_trial)
    
  }
  
  stims %>%
    bind_rows(tibble(item = 1, trial = 1:n, count = trial)) %>%
    filter(trial > 0)
}

# xsit_conditions <- crossing(C = c(1, 2, 4),
#                             M = c(8, 64, 256),
#                             p = seq(.25, 1, .01)) 
# 
# xsit_ns <- xsit_conditions %>%
#   rowwise() %>%
#   mutate(n = xsit_min_n(p, C, M, .75))
# 
#   
# ns <- xsit_conditions %>%
#   left_join(teach_ns) %>%
#   mutate(type = "teach") %>%
#   bind_rows(xsit_ns %>% mutate(type = "xsit"))
# 
# ggplot(ns, aes(x = p, y = n, color = type)) + 
#   facet_grid(C ~ M) +
#   geom_point()
# 
# 
# plot_tmp <- ns %>% 
#   mutate(howHard = if_else(C==1 & M == 8, "easiest", "NA"),
#          howHard = if_else(C==4 & M == 256, "hardest", howHard)) %>% 
#   select(-C, -M) %>%
#   filter(howHard != "NA") %>%
#   spread(howHard, n) %>% 
#   mutate(type = factor(type, levels=c("xsit","teach"),
#                             labels=c("XSL","Teaching"), ordered=TRUE)) %>%
#   mutate(hypCommunication = easiest + sample(c(1,2), 1))
# 
# label_data <- tibble(p = c(.75, .85, .85), 
#                      type = c("XSL", "Teaching", "Communication"), easiest = c(5.5, 1.5, 2.35))
# 
# 
# 
# ggplot(plot_tmp, aes(x = p, y = easiest, label=type)) + 
#   geom_ribbon(data= (plot_tmp %>% filter(type=="XSL")), aes(x=p,ymin=easiest, ymax=hardest), 
#               color="grey", alpha=.5, fill="darkgrey") +
#   geom_ribbon(data= (plot_tmp %>% filter(type=="Teaching")), aes(x=p,ymin=easiest, ymax=easiest), color="green3") +
#   #hypotheszied teaching data, v rough for hypothetical findings plot
#   geom_line(data= (plot_tmp %>% filter(type=="Teaching")), aes(x=p,y=hypCommunication), color="red") +
#   labs(x="Learning Parameter", y = "Model Estimated Number of \n Exposures to Learn One Word") +
#   geom_text(data = label_data, color=c('darkgrey', "green3", "red"))
# 
# 
# 
# 
# ggplot(xsit_ns, aes(x = p, y = n, color = as.factor(M))) + 
#   facet_grid(. ~ C) +
#   geom_point() 


C <- 4
M <- 16
p <- .5
alpha <- 1

crossit_probs <- function(p, C, M) {
  generate_xsit_stims(C, M) %>%
    mutate(assoc = count * (p/C),
           target = item == 1,
           str = exp(alpha * assoc)) %>%
    group_by(trial, target) %>%
    summarise(str = sum(str)) %>%
    spread(target, str) %>%
    mutate(prob = `TRUE` / (`TRUE` + `FALSE`)) %>%
    select(trial, prob) %>%
    rename(n = trial) %>%
    mutate(p = p)
}

cross_props <- map_df(seq(.25,.75,.25), ~crossit_probs(.x, C, M))

# ggplot(cross_props, aes(x = n, y = prob, color = as.factor(p))) + 
#   geom_line()
```

personalized communication
```{r setup-communication} 
MAX_DELAY <- 10
U <- 100

P <- 70
S <- 0
alpha <- 2
lambda <- .5
p <- .6


teach_outcome <- function(n = 1, p = .6) {
  1 - (1-p) ^ n
}

# this can't contain ps if it's going to get logged
speak_success_u <- function(S = 0) {
 log(max(U - S, 0) + .001)
}

speak_fail_u <- function() {
 log(max(0 - S, .001))
}

point_u <- function(P = 30) {
  log(max(U - P, 0) + .001)
}

teach_u <- function(P = 30, S = 0) {
  log(max(U - P - S, 0) + .001)
}

discount <- function(delay, lambda = .5) {
  lambda ^ delay
}

act_u <- function(delay, k, n, p = .6) {
  
  if(delay > MAX_DELAY) {
    expected_util <- 0
    teach_p <- NA
    speak_p <- NA
  }
  
  else {
    if(k == 0) {
      
      speak_util <- speak_fail_u() +
        discount(delay + 1) * 
        (act_u(delay + 1, k = 0, n = 0, p) %>% pull(eu))
      
      point_util <- point_u() + 
        discount(delay + 1) * 
        (act_u(delay + 1, k = 0, n = 0, p) %>% pull(eu))
      
      teach_util <- teach_u() + 
        discount(delay + 1) * 
        (act_u(delay + 1, teach_outcome(), n = 1, p) %>% pull(eu))
      
    } else if(k == 1) {
       speak_util <- speak_success_u() + 
                       discount(delay + 1) * 
                       (act_u(delay + 1, k = 1, n = 0, p) %>% pull(eu))

       point_util <- point_u() + 
                       discount(delay + 1) * 
                       (act_u(delay + 1, k = 1, n = 0, p) %>% pull(eu))
       
       teach_util <- teach_u() + 
         discount(delay + 1) * 
         (act_u(delay + 1, k = 1, n = n + 1, p) %>% pull(eu))
      
    } else {
      speak_util <- (k * (speak_success_u() +
                           discount(delay + 1) * 
                           (act_u(delay + 1, k = 1, n = 0, p) %>% pull(eu)))) +
        ((1-k) * (speak_fail_u() + discount(delay+1) * 
                       (act_u(delay + 1, k = 0, n = 0, p) %>% pull(eu))))
      
      point_util <- point_u() + discount(delay + 1) * 
         (act_u(delay + 1, k, n, p) %>% pull(eu))
            
      teach_util <- teach_u() + discount(delay + 1) * 
         (act_u(delay + 1, teach_outcome(n + 1, p), n = n + 1, p) %>% pull(eu))
    }
   
   teach_p <- exp(alpha * teach_util) / (
     exp(alpha * teach_util) + (exp(alpha * speak_util) + 
                                  (exp(alpha * point_util))))
   
   speak_p <- exp(alpha * speak_util) / (
     exp(alpha * speak_util) + (exp(alpha * point_util) + 
                                  (exp(alpha * teach_util))))
   
   expected_util <- teach_p * teach_util + (speak_p) * speak_util +
     (1 - speak_p - teach_p) * point_util
  
#  print(expected_util)
  }
   
   tibble(delay = delay,
          n = n,
          eu = expected_util,
          pspeak = speak_p,
          ppoint = 1 - speak_p - teach_p,
          pteach = teach_p)
   
}
```

```{r propose-but-verify}
generate_propose_stims <- function(C = 4, M = 16, n = 100) {
  replicate(n, enframe(sample(2:M, C - 1)), simplify = F) %>%
    bind_rows(.id = "trial") %>%
    select(-name) %>%
    rename(object = value) %>%
    mutate(trial = as.numeric(trial)) %>%
    bind_rows(tibble(trial = 1:n, object = 1))
}

propose_but_verify <- function(p = .6, C = 4, M = 16, n = 100) {
  stims <- generate_propose_stims(C, M, n)
  
  guess <- 0
  trial <- 0
  
  for(i in 1:n) {
    if(guess == 1) {
      trial <- i - 1
      break
    }
    
    trial_stims <- stims %>%
      filter(trial == i) %>%
      pull(object)
    
    if(!guess %in% trial_stims) {
      selected <- sample(trial_stims, 1)
      if(rbinom(1, 1, p))
        guess <- selected
      else
        guess <- 0
    }
    
  }
  
  return(trial)
}

propose_but_verify <- function(p = .6, C = 4, M = 16, n = 100, 
                                        nguesses = 4) {
  stims <- generate_propose_stims(C, M, n)
  
  guesses <- 0
  trial <- 0
  
  for(i in 1:n) {
    
    if(length(guesses) == 1 && guesses == 1) {
      trial <- i
      break
    }
    
    trial_stims <- stims %>%
      filter(trial == i) %>%
      pull(object)
    
    matches <- intersect(guesses, trial_stims)
    
    if(is_empty(matches)) {
      selected <- sample(trial_stims, min(nguesses, length(trial_stims)))
      
      kept <- selected[as.logical(rbinom(length(selected), 1, p))]
                         
      if(is_empty(kept))
        guesses <- 0
      else
        guesses <- kept
    } else {
      guesses <- matches
    }
    
  }
  
  return(trial)
}


pbv_samples <- function(reps = 1000, p = .6, C = 4, M = 16, n = 100, 
                        nguesses = 1) {
  replicate(reps, propose_but_verify(p, C, M, n, nguesses)) %>%
    enframe() %>%
    select(-name) %>%
    mutate(p = p) %>%
    rename(n = value)
}

pbv_props_4 <- map(c(.25, .5, .75), ~pbv_samples(p = .x, nguesses = 4)) %>%
  bind_rows() %>%
  group_by(p, n) %>%
  summarise(prob = n()) %>%
  complete(n = full_seq(1:100, 1), p, fill = list(prob =0)) %>%
  arrange(p, n) %>%
  mutate(prob = prob/sum(prob)) %>%
  mutate(prob = cumsum(prob)) 


pbv_props_1 <- map(c(.25, .5, .75), ~pbv_samples(p = .x, nguesses = 1)) %>%
  bind_rows() %>%
  group_by(p, n) %>%
  summarise(prob = n()) %>%
  complete(n = full_seq(1:100, 1), p, fill = list(prob =0)) %>%
  arrange(p, n) %>%
  mutate(prob = prob/sum(prob)) %>%
  mutate(prob = cumsum(prob)) 

AUC(pbv_props_1$prob, pbv_props_4)

all_pbv_props <- pbv_props_1 %>%
  mutate(nguesses = 1) %>%
  bind_rows(mutate(pbv_props_4, nguesses = 4))

ggplot(all_pbv_props, aes(x = n, y = prob, color = as.factor(p))) + 
  geom_line(aes(linetype = as.factor(nguesses))) + 
  scale_color_brewer(palette = "Set1")

ggsave("pbvs.pdf")
```

```{r simulate-communcation}
MAX_DELAY <- 4

communication_probs <- function(p) {

  teach_probs <- map_df(0:50, ~act_u(delay = 0, teach_outcome(.x, p), 
                                     n = .x, p)) %>%
    select(-delay, -eu) #%>%
   # mutate(know_prob =  teach_outcome(n + 1, p = p))
  
  
  teach_counts <- tibble(n = 0, prob = 1)
  
  MAX_TRIAL <- 50
  unknown_remaining <- function(trials, unknowns, teach_counts) {
    
    trial = last(trials)
    unknown = last(unknowns)
    
    if(trial == MAX_TRIAL)
      return(tibble(trial = trials, prob = 1 - unknowns))
    
    updated_counts <- teach_counts %>%
      left_join(teach_probs, by = "n") %>%
      gather(modality, outcome, pspeak, ppoint, pteach) %>%
      mutate(new_prob = prob * outcome)
    
    taught <- updated_counts %>% 
      filter(modality == "pteach") %>% 
      mutate(new_prob = new_prob * p) %>%
      summarise(new_prob = sum(new_prob)) %>%
      pull()
      
    
    unknown <- unknown * (1 - taught)
    
    teach_counts <- updated_counts %>%
      mutate(new_prob = if_else(modality == "pteach",
                               new_prob * (1 - p), new_prob),
             n = if_else(modality == "pspeak", 0,
                         if_else(modality == "pteach", n + 1, n))) %>%
      select(-outcome, -modality, -prob) %>%
      group_by(n) %>%
      rename(prob = new_prob) %>%
      summarise(prob = sum(prob)) %>%
      mutate(prob = prob / sum(prob))
    
    return(unknown_remaining(c(trials, trial + 1), 
                             c(unknowns, unknown),
                             teach_counts))
  }

unknown_remaining(0, 1, teach_counts) %>%
  mutate(p = p)
}



communication_props <- map_df(c(.25, .5, .75), ~communication_probs(.x))
```



```{r plot}
all_props <- communication_props %>%
  mutate(type = "Communication") %>% 
  rename(n = trial) %>%
  bind_rows(mutate(teach_props, type = "Teaching")) %>%
  bind_rows(mutate(cross_props_2_24, type = "XSit: 2 competitors")) %>%
  bind_rows(mutate(cross_props_6_24, type = "XSit: 6 competitors")) %>%
  mutate(type = factor(type, levels = c("Teaching", "Communication", "XSit: 2 competitors", "XSit: 6 competitors")))
  bind_rows(mutate(teach_props, type = "teaching")) %>%
#  bind_rows(mutate(cross_props, type = "xsit")) %>%
  bind_rows(mutate(pbv_props, type = "pbv")) %>%
  mutate(type = factor(type, levels = c("teaching", "communication", 
                                         "pbv")))


ggplot(all_props, aes(x = n, y = prob, color = as.factor(p))) + 
  geom_line(aes(linetype = type)) + 
  scale_color_brewer(palette = "Set1") +
  scale_linetype_manual(values=c("solid", "dotdash", "dashed"))

#ben's plot
# xsit is range of cases 2 competitors to 6
  # two xsits for .25 and .75 p value
# teachinga nd comm show range of ps, range of learning paramaeters

all_props %>%
  filter(p != .5) %>%
  # mutate(p =  paste0("learning parameter = ", p)) %>%
  ggplot(aes(x = n, y=prob, color = type)) + 
  geom_line() +
  # geom_line(aes(linetype = as.factor(p))) + 
  labs(y="Probability of Learning", x="Number of Exposures") +
  # scale_linetype_manual(values=c("dotdash", "solid")) +
  scale_color_manual(values=c("green3", "red", "blue3", "lightblue")) +
  facet_grid(p~.)
  

all_props %>%
  filter(p != .5,
         !grepl("xsit",type)) %>%
  spread(p, prob) %>%
  ggplot(aes(x = n, color = type, fill=type)) + 
  geom_ribbon(data= cross_props %>% filter(p == .25), aes(x = n, ymin = prob1, ymax=prob), fill="grey", alpha=.5) +
  geom_ribbon(data= cross_props %>% filter(p == .75), aes(x = n, ymin = prob1, ymax=prob), fill="darkgrey", alpha=.5) +
  geom_ribbon(aes(ymin=`0.25`, ymax=`0.75`), alpha=.8) +
  # facet_grid(p~.) +
  # geom_line(aes(linetype = as.factor(p))) + 
  labs(y="Probability of Learning", x="Number of Exposures") +
  scale_linetype_manual(values=c("solid", "dotdash", "dashed"))+
  scale_color_manual(values=c("red", "green3", "darkgrey"))+
  scale_fill_manual(values=c("green3", "red", "darkgrey"))


all_props_spread <-  all_props %>%
  spread(p, prob)

#range of learning p values for all things...
# 2 xsit models

ggplot(all_props_spread, aes(x = n, color = type, fill=type)) + 
  geom_ribbon(data= all_props_spread %>% filter(grepl("xsit",type)), aes(x = n, ymin = `0.25`, ymax=`0.75`), alpha=.5) +
  geom_ribbon(data= all_props_spread %>% filter(grepl("comm",type)), aes(x = n, ymin = `0.25`, ymax=`0.75`), alpha=.7) +
  geom_ribbon(data= all_props_spread %>% filter(grepl("teach",type)), aes(x = n, ymin = `0.25`, ymax=`0.75`), alpha=.8) +
  # facet_grid(p~.) +
  # geom_line(aes(linetype = as.factor(p))) + 
  labs(y="Probability of Learning", x="Number of Exposures") +
  scale_color_manual(values=c("red", "green3", "grey", "darkgrey")) +
  scale_fill_manual(values=c("red", "green3", "lightgrey","darkgrey"))




```

